export const SET_CURRENT_DISH = 'SET_CURRENT_DISH';
export const REMOVE_CURRENT_DISH = 'REMOVE_CURRENT_DISH';
export const SET_APP_LOADING = 'SET_APP_LOADING';

/* API calls */
export const API_CALL_FETCH_CATEGORIES = 'API_CALL_FETCH_CATEGORIES';
