export const INCREMENT_TEST_DATA = 'INCREMENT_TEST_DATA';
export const DECREMENT_TEST_DATA = 'DECREMENT_TEST_DATA';
export const SET_CURRENT_DISH = 'SET_CURRENT_DISH';
export const REMOVE_CURRENT_DISH = 'REMOVE_CURRENT_DISH';
export const ENABLE_APP_LOADING = 'ENABLE_APP_LOADING';
export const DISABLE_APP_LOADING = 'DISABLE_APP_LOADING';

/* API calls */
export const API_CALL_FETCH_CATEGORIES = 'API_CALL_FETCH_CATEGORIES';
